name: golangci-lint

on:
  push:
    branches: [ main, release-** ]
  pull_request:
    branches: [ main, release-** ]
  workflow_dispatch:

permissions:
  contents: read

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 EXCLUDE_ENTERPRISE: true

jobs:
  down-migrations:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: "focalboard"
      - name: assert that down migrations are SELECT 1 scripts
        run: |
          cd focalboard
          echo 'SELECT 1;' > downmigration
          for file in server/services/store/sqlstore/migrations/*.down.sql; do diff -Bw downmigration $file; done

  golangci:
    name: plugin
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: "focalboard"
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: focalboard/go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20  # v9.2.0
        with:
          version: v2.8.0
          working-directory: focalboard/server
